name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  gap: ^3.0.1
  intl: ^0.19.0
  file_picker: ^8.1.2
  equatable: ^2.0.5  
  flutter:
    sdk: flutter
  stacked: ^3.4.2    
  stacked_services: ^1.4.0
  logger: ^1.4.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.1  
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0    
  mocktail: ^1.0.4
  stacked_generator: ^1.3.3  
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
